# Generated by Django 4.2.1 on 2023-05-11 14:11

from django.db import migrations, models
import django.db.models.deletion
import secured_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_employee_first_name_remove_employee_last_name'),
        ('patient', '0003_alter_patient_allergies_alter_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_visit', secured_fields.fields.EncryptedTextField()),
                ('visit_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('visit_notes', secured_fields.fields.EncryptedTextField(blank=True)),
                ('blood_pressure_systolic', secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure_diastolic', secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heart_rate', secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('respiratory_rate', secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature', secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', secured_fields.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.employee')),
            ],
        ),
    ]
