# Generated by Django 4.2.1 on 2023-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=models.SlugField(default='slug123', unique=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='slug',
            field=models.SlugField(default='slug123', unique=True),
        ),
    ]
