# Generated by Django 4.2.1 on 2023-05-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patient_slug_alter_visit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
